name: VehicleCfg
services:

  # Nginx for current project
  nginx:
    container_name: nginx
    #restart: always
    image: nginx:latest
    ports:
      - 80:80
    #  - 443:443
    volumes:
      - ./docker/nginx/hosts:/etc/nginx/conf.d:delegated
      - ./www:/var/www/html:delegated
      - ./docker/logs/nginx:/var/log/nginx:delegated
      - vendor-dir:/var/www/html/vendor
    #command: [nginx-debug, '-g', 'daemon off;']
    networks:
      - backend

  # Php (fpm) for current project
  php:
    container_name: php
    build:
      context: ./docker/php
      dockerfile: Dockerfile.dev
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./www:/var/www/html:delegated
      - vendor-dir:/var/www/html/vendor
    #restart: always
    networks:
      - backend
      
  mysql:
    container_name: mysql
    build:
      context: ./docker/mysql
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33006:3306
    #restart: always
    networks:
      - backend
      
  setup:
    container_name: setup
    build:
      context: ./docker/setup
      dockerfile: Dockerfile.dev
    volumes:
        - ./www:/var/www/html:delegated
        - vendor-dir:/var/www/html/vendor
    networks:
      - backend
    
networks:
  backend:
  
volumes:
  vendor-dir:
