FROM php:8.3-cli

# Install system dependencies and PHP extensions
RUN apt-get update && apt-get install -y \
    libzip-dev \
    zip \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
  && docker-php-ext-install zip mysqli pdo_mysql \
  && docker-php-ext-configure gd --with-freetype --with-jpeg \
  && docker-php-ext-install -j$(nproc) gd \
  && docker-php-ext-install exif
  
RUN apt-get install npm -y

# Copy Composer from the official Composer image
COPY --from=composer:2.8.5 /usr/bin/composer /usr/bin/composer

COPY install.sh /app/install.sh

WORKDIR /var/www/html

ENTRYPOINT ["/app/install.sh"]